# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: topolog's tech blog
description: Things your mom didn't tell you about iOS
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dmtopolog.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dmtopolog
github_username:  DmIvanov
google_analytics: UA-127243344-1

# logo: /images/logo.jpg

# paginate: 20
# paginate_path: /page:num/
read_time: true
future: true

# Build settings
# theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme

plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag

author: topolog

tag_archive_path: "/tags/#"

jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/dmtopolog
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/dmivanov
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/ivanovdmitrii/
    icon: fab fa-linkedin
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square
